FROM golang:1.24-alpine

WORKDIR /app

ARG APP_ENV
ARG BACK_VERSION
ARG BACK_BUILD_TIME
ARG BACK_COMMIT_SHA

# go env / module cache を活かす
COPY go.mod go.sum ./
RUN go mod download

# ソースは volume でマウントされる想定
EXPOSE 8080

CMD ["go", "run", "./cmd/server"]
