FROM golang:1.24-alpine

WORKDIR /app

ARG APP_ENV
ARG APP_VERSION
ARG BUILD_TIME
ARG GIT_COMMIT

# go env / module cache を活かす
COPY go.mod go.sum ./
RUN go mod download

# ソースは volume でマウントされる想定
EXPOSE 8080

CMD ["go", "run", "./cmd/server"]
